### ISSUE TITLE
Errors when loading boards page with items

### ISSUE THREAD

**Issue by kfranzen** [b33rTiger/mytodoapp#3]
MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: todos.lists.$name_1  dup key: { : "first list" }
    at Function.MongoError.create (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb/lib/utils.js:114:22)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb/lib/collection.js:597:23
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb/lib/bulk/unordered.js:469:9
    at resultHandler (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb/lib/bulk/unordered.js:416:5)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb-core/lib/topologies/server.js:780:13
    at Callbacks.emit (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
CastError: Cast to ObjectId failed for value "undefined" at path "_list"
    at MongooseError.CastError (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/error/cast.js:19:11)
    at ObjectId.cast (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/schema/objectid.js:134:13)
    at ObjectId.castForQuery (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/schema/objectid.js:173:17)
    at module.exports (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/cast.js:205:32)
    at Query.cast (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/query.js:2540:10)
    at Query.find (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/query.js:1090:10)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/query.js:2141:21
    at new Promise.ES6 (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/promise.js:45:3)
    at Query.exec (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/query.js:2134:10)
    at exports.index (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/app/controllers/todo_controller.js:14:4)
    at Layer.handle [as handle_request](/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:330:12)
Error: No _id found on document!
    at model._where [as $__where](/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/model.js:652:12)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/model.js:707:23
    at new Promise.ES6 (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/promise.js:45:3)
    at model.remove (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/model.js:706:37)
    at exports.destroy (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/app/controllers/todo_controller.js:65:8)
    at Layer.handle [as handle_request](/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:277:22
    at param (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:271:10)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/app/authentication_middleware.js:19:9
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/jsonwebtoken/index.js:155:18
Error: No _id found on document!
    at model._where [as $__where](/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/model.js:652:12)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/model.js:707:23
    at new Promise.ES6 (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/promise.js:45:3)
    at model.remove (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/mongoose/lib/model.js:706:37)
    at exports.destroy (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/app/controllers/todo_controller.js:65:8)
    at Layer.handle [as handle_request](/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:277:22
    at param (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/express/lib/router/index.js:271:10)
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/app/authentication_middleware.js:19:9
    at /Users/kirk/Code/learntech/student_projects/john/mytodoapp/todos/node_modules/jsonwebtoken/index.js:155:18

**Comment by kfranzen** [comment]
Looks like this is due to data left by previous runs or by test runs.
